spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskservice?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: Task
server:
  port: 8081
