spring:
  datasource:
    url: jdbc:mysql://mysql-standalone:3306/paymentservice?createDatabaseIfNotExist=true #jdbc:mysql://localhost:3306/paymentservice?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      token-info-uri: http://oauth-server:9191/oauth/check_token #http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin