spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentservice?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
