spring:
  cloud:
    gateway:
      routes:
        - id: driver #driver-service
          uri: lb://driver #lb://Driver
          predicates:
            - Path=/services/drivers/**
        - id: offence #offence-service
          uri: lb://offence #lb://OFFENCE
          predicates:
            - Path=/services/offences/**,/services/fines/**
        - id: officer
          uri: lb://officer
          predicates:
            - Path=/services/officers/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/services/payments/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
    discovery:
      enabled: true
  application:
    name: API-GATEWAY
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
server:
  port: 8989


