spring:
  datasource:
    url: jdbc:mysql://mysql-standalone:3306/driverservice?createDatabaseIfNotExist=true #jdbc:mysql://localhost:3306/driverservice?createDatabaseIfNotExist=true  #url: jdbc:mysql://localhost:3306/driverservice?createDatabaseIfNotExist=true
    username: root #janitha #root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: driver
security:
  oauth2:
    resource:
      token-info-uri: http://oauth-server:9191/oauth/check_token #http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
